disabled_rules:
  - file_length
  - force_cast
  - force_try
  - function_parameter_count
  - identifier_name
  - large_tuple
  - line_length
  - shorthand_operator
  - type_body_length
  - type_name
  - legacy_objc_type

function_body_length:
  warning: 110
  error: 150

cyclomatic_complexity:
  ignores_case_statements: true

opt_in_rules:
  - array_init
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - direct_return
  - empty_collection_literal
  - empty_count
  - empty_string
  - fatal_error_message
  - final_test_case
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - last_where
  - legacy_multiple
  - legacy_objc_type

included:
  - pos-app-ios
  - pos-app-iosTests
  - pos-app-iosUITests

excluded:
  - .bundle
  - .github
  - .idea
  - .project-metadata
  - .vendor
  - .vscode
  - Assets
  - Carthage
  - DerivedData
  - fastlane
  - readme_images
  - PackageDependency
  - TestPlans
  - pos-app-iosUITests/Helpers/UITestBase.swift
